### ISSUE TITLE
question: how does oneOf shrink?

### ISSUE THREAD

**Issue by BrianHicks** [Janiczek/elm-minithesis#13]
just what it says on the tin. How does `oneOf` shrink with this shrinking strategy? In `elm-exploration/test` fuzzing, it seems like each item is shrunk independently. Is that different here (e.g. shrinking towards the first item in the list?)

**Comment by Janiczek** [comment]
Thanks, I [made this more explicit in the docs](https://github.com/Janiczek/elm-minithesis/commit/1d98f58f65747be0c78ad881340f31dc16d05bc4) and [added tests for it](https://github.com/Janiczek/elm-minithesis/commit/118ff0989ff93c9dab4571f2c813b1b0ad55d212) :) Does that answer the question?

**Comment by BrianHicks** [comment]
😍 fantastic! Yes, thank you!
